services:
  sqld:
    image: ghcr.io/tursodatabase/libsql-server:latest
    volumes: [ "sqld-data:/var/lib/sqld" ]
    restart: unless-stopped
    healthcheck:
        test: [ "CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/8080" ]
        interval: 5s
        timeout: 3s
        retries: 10
        start_period: 5s

  migrate:
      image: ghcr.io/jstmemit/migrate
      build:
          context: .
          dockerfile: packages/db/Dockerfile
      env_file:
          - ".env.docker"
      depends_on:
          sqld:
              condition: service_healthy
      restart: "no"

  redis:
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes: [ "redis-data:/data" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  bot:
    image: ghcr.io/jstmemit/bot
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    env_file:
      - ".env.docker"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      sqld:
        condition: service_started

  website:
      image: ghcr.io/jstmemit/website
      build:
          context: .
          dockerfile: apps/website/Dockerfile
      restart: unless-stopped
      ports: [ "4321:4321" ]

  meme-generator:
    image: ghcr.io/jstmemit/meme-generator
    build:
      context: .
      dockerfile: apps/meme-generator/Dockerfile
    env_file:
      - ".env.docker"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      sqld:
        condition: service_started

  whisper:
      image: hwdsl2/whisper-server
      container_name: whisper
      restart: unless-stopped
      volumes:
          - whisper-data:/var/lib/whisper
          - ./.env.docker:/whisper.env:ro

volumes:
  sqld-data:
  redis-data:
  whisper-data:
      name: whisper-data